FROM node:20.18.1-alpine3.20

WORKDIR /app

COPY package*.json ./

#RUN npm install --global --production windows-build-tools
RUN npm ci
RUN npm install -g nodemon

COPY ./ ./

EXPOSE 3000
EXPOSE 9229

CMD ["nodemon", "--inspect=0.0.0.0:9229", "index.js"]